### PR TITLE
Updates links in README.

### PR DESCRIPTION
**Pull request by jejacks0n**
This might help some people sort things out at the moment.

### CODE REVIEW

**Comment by shawnblakesley** [comment]
@jejacks0n thanks for adding this. I'm not sure if you've had a chance, but you probably should still sign the contributing license agreement just in case it matters. If you do then I may be able to approve this even though I technically don't work for Anki anymore. 🤷‍♂

**Comment by jejacks0n** [comment]
Thanks @shawnblakesley -- I signed the IC agreement. Sorry about the job (the company I was at closed on Monday the 30th as well). 🤷‍♂

**Comment by shawnblakesley** [comment]
Thanks. Such is the way of things. Hope it all works out for you as well.
Even post-Anki I'll always have a soft spot for our little robot buddy.

**Comment by rmcolbert** [comment]
Shawn, I think I can speak for the entire Vector community in thanking you for the work you've done and we'd welcome you if you'd like to join the Discord community that has grown out of the love for Vector & Cozmo. [https://discord.gg/zZuDHRK](https://discord.gg/zZuDHRK)

**Comment by jejacks0n** [comment]
@shawnblakesley Same, and thanks for all your effort on Vector. I'm exploring options and trying to figure out if it's at all possible from a community perspective to shift vector to using wit.ai for the NLP (or similar). I know you shifted to the NLP team -- so, avoiding any legal issues for you, do you feel it would be possible from the SDK perspective to get anything like that wired up? And if not, what options do you think all these little guys have to retain some of their NLP functionality long term for those users willing to invest some effort in doing the training?

**Comment by K7715** [comment]
Yes @rmcolbert and @jejacks0n I agree, and if I may add to that with another thank you; from me to @shawnblakesley .

**Comment by K7715** [comment]
I am not as skilled as you awesome folks are about this. But I am passionate to help in any way that I can. What Anki did sucks and I have great empathy for the employees. You’re all in my prayers. I am only apart of this conversation to update the good folks on Reddit of any good updates. And I also have a soft spot for our Vectors out there.

**Comment by rmichaelsm** [comment]
I echo their sentiment.  Vector has been a lot of fun for me.  He's our pet for sure.  I have reached out to people who used Cosmos (and I think Vector) in training classes for programming and math (algebra/trig).  I hope they can present something to some Rich Foundations or Colleges that may spark some interest and a revival of sorts.  They are on the cusp of great things.  I am going to work some with the sign language code that was in the experimental folder.  Things like that could be great for teaching coding, etc.

**Comment by shawnblakesley** [comment]
Thanks everybody (@rmcolbert @jejacks0n @K7715 @rmichaelsm). In the end Anki was a collection of amazing people that wanted to make an awesome robot. My love for every one of them cannot be understated, and I have no doubt we'll all land on our feet somewhere (hopefully surrounded by fellow Ankians).

@rmcolbert: I may end up joining the discord down the road, but I'm mainly trying to decompress for a couple days here. I love the community that formed around our little robot companion.

@jejacks0n: Without some of the work that was planned for the Robot 1.7, I don't think capturing the audio stream is possible. Without an audio stream, you don't have anything to send to Wit.

**Comment by jejacks0n** [comment]
@shawnblakesley It's a sad day for everybody at Anki. Saying goodbye to a team is rough stuff, especially when everybody is so passionate about the same thing.

That's the information I was looking to get. Thanks. My follow up questions are
- how far away from launch was v1.7?
- anybody still at Anki want to try to ship v1.7 before shutting everything down?
- anybody not at Anki officially anymore want to share the best way to root a device? 🤣

**Comment by shawnblakesley** [comment]
@jejacks0n I think that's 3 for 3 where I don't have an answer for you, sorry.

**Comment by rmichaelsm** [comment]
we have a bunch of people both on the anki forums and 
[https://www.reddit.com/r/AnkiVector](url)

**Comment by Kinvert** [comment]
Thanks for all your help @shawnblakesley !

Is there anything you can say about what customers can do to keep as much functionality as possible with their Vectors?

I said this elsewhere but you may not have seen it. I've been through multiple layoffs and every single time I found myself in an even better opportunity not too long after. These things are often a blessing in disguise.

**Comment by shawnblakesley** [comment]
@Kinvert I don't have any information about future Vector functionality. I would just say I recommend not clearing user data or hard resetting if there are any issues. That and save your guid, cert, etc. once you've set up the SDK. Wish I knew more.

Thanks for the kind words. This is actually my 3rd or 4th time through this kinda thing (just not this scale). I know it'll all work out for everyone. I always choose jobs based on passion, and I wouldn't change my mind if I had a second chance to choose Anki.

**Comment by LudwigVonChesterfield** [comment]
While I somehow feel bad for me not getting into this convo earlier,

I would also like to thank you greatly for all the good work done. Vector is quite a piece of AI cake, and what's more you made people love him, even consider him a pet. Great work done.

**Comment by olia-bn** [comment]
Good luck to you @shawnblakesley and thank you for all your effort and hard work!

**Pull request merged**
